/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocmascotas.view;

import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import static poc.mascotas.service.ServicioMascota.TAM_REGISTRO;

/**
 *
 * @author Lenovo
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        barraAdicionar = new javax.swing.JRadioButtonMenuItem();
        menuMascota = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setAutoscrolls(true);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        menuArchivo.setBackground(new java.awt.Color(255, 204, 255));
        menuArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuArchivo.setForeground(new java.awt.Color(51, 0, 51));
        menuArchivo.setText("Archivo");
        menuArchivo.setToolTipText("");

        jRadioButtonMenuItem1.setBackground(new java.awt.Color(255, 204, 255));
        jRadioButtonMenuItem1.setForeground(new java.awt.Color(51, 0, 51));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Salir");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraSalir(evt);
            }
        });
        menuArchivo.add(jRadioButtonMenuItem1);

        jMenu2.setBackground(new java.awt.Color(255, 204, 255));
        jMenu2.setText("Modificar/Buscar");

        jMenuItem3.setBackground(new java.awt.Color(255, 204, 255));
        jMenuItem3.setText("Registros");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuArchivo.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(255, 204, 255));
        jMenu1.setText("Nuevo");

        barraAdicionar.setBackground(new java.awt.Color(255, 204, 255));
        barraAdicionar.setForeground(new java.awt.Color(51, 0, 51));
        barraAdicionar.setSelected(true);
        barraAdicionar.setText("Registro");
        barraAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraAdicionarActionPerformed(evt);
            }
        });
        jMenu1.add(barraAdicionar);

        menuArchivo.add(jMenu1);

        jMenuBar2.add(menuArchivo);

        menuMascota.setBackground(new java.awt.Color(255, 204, 255));
        menuMascota.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuMascota.setForeground(new java.awt.Color(51, 0, 51));
        menuMascota.setText("Mascotas");

        jMenuItem1.setBackground(new java.awt.Color(255, 204, 255));
        jMenuItem1.setText("Listar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraListar(evt);
            }
        });
        menuMascota.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(255, 204, 255));
        jMenuItem2.setText("camtidad de registros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuMascota.add(jMenuItem2);

        jMenuBar2.add(menuMascota);

        menuAyuda.setBackground(new java.awt.Color(255, 204, 255));
        menuAyuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuAyuda.setForeground(new java.awt.Color(51, 0, 51));
        menuAyuda.setText("Ayuda");

        jRadioButtonMenuItem2.setBackground(new java.awt.Color(255, 204, 255));
        jRadioButtonMenuItem2.setForeground(new java.awt.Color(51, 0, 51));
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Acerca de ....");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraAyuda(evt);
            }
        });
        menuAyuda.add(jRadioButtonMenuItem2);

        jMenuBar2.add(menuAyuda);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraAdicionarActionPerformed
        GUIAdicionar gui = new GUIAdicionar();
        gui.setVisible(true);
        
    }//GEN-LAST:event_barraAdicionarActionPerformed

    private void barraAyuda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraAyuda
         JOptionPane.showMessageDialog(this, "desarrollado por: laura sofia carvajal, juan pablo chacon,  juan daniel tapiero");
    }//GEN-LAST:event_barraAyuda

    private void barraSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraSalir
        System.exit(0);
    }//GEN-LAST:event_barraSalir

    private void barraListar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraListar
        GUIListar gui = new GUIListar();
        gui.setVisible(true);
    }//GEN-LAST:event_barraListar

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       try {
        
        
            RandomAccessFile file = new RandomAccessFile("data//mascota.dat", "rw");
            file.seek(0);
            long tamaño = file.length();

            long numeroRegistros = (tamaño/TAM_REGISTRO);
            
            
            Object[] opciones = {"Contar"};

            int seleccion = JOptionPane.showOptionDialog(
                    null,                                  
                    "Cantidad de registros",               
                    "Información",                        
                    JOptionPane.DEFAULT_OPTION,            
                    JOptionPane.QUESTION_MESSAGE,       
                    null,                                 
                    opciones,                             
                    opciones[0]                           
            );

            // Evaluamos si el usuario presionó "Contar"
            if (seleccion == 0) {
                JOptionPane.showMessageDialog(this, numeroRegistros);}
           } catch (Exception ex) {}
           
           ;

    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        GUIBuscarEnRegistro gui = new GUIBuscarEnRegistro();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem barraAdicionar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuMascota;
    // End of variables declaration//GEN-END:variables
}
